-keep class com.google.android.play.core.splitcompat.** { *; }
-keep class com.google.android.play.core.splitinstall.** { *; }
-keep class com.google.android.play.core.tasks.** { *; }
-keep class com.squareup.okhttp.** { *; }
-keep class java.lang.reflect.AnnotatedType { *; }
